layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(rgba32f, binding = 0) uniform image2DArray tex0;
layout(rgba32f, binding = 1) uniform image2D tex1;

void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    imageStore(tex0, ivec3(id, 0), vec4(id, 0.0, 1.0));
    imageStore(tex0, ivec3(id, 1), vec4(id, 0.1, 1.0));
    imageStore(tex0, ivec3(id, 2), vec4(id, 0.2, 1.0));
    imageStore(tex0, ivec3(id, 3), vec4(id, 0.3, 1.0));
    imageStore(tex0, ivec3(id, 4), vec4(id, 0.4, 1.0));
    imageStore(tex0, ivec3(id, 5), vec4(id, 0.5, 1.0));
    imageStore(tex0, ivec3(id, 6), vec4(id, 0.6, 1.0));
    imageStore(tex0, ivec3(id, 7), vec4(id, 0.7, 1.0));
    imageStore(tex0, ivec3(id, 8), vec4(id, 0.8, 1.0));
    imageLoad(tex1, id);
}