#include <Globals.hpp>

layout(local_size_x = THREAD_NUMBER, local_size_y = THREAD_NUMBER, local_size_z = 1) in;

layout(rgba32f, binding = BUFFERS_UNIT) uniform image2DArray buffers;

layout(location = 0) uniform int to;
layout(location = 1) uniform int from;

void main() {
    ivec2 id = ivec2(gl_GlobalInvocationID.xy);
    vec4 data = imageLoad(buffers, ivec3(id, from));
    imageStore(buffers, ivec3(id, to), data);
}
