#pragma once

#define BUFFERS_UNIT 0
#define DEBUG_VIEW_UNIT 1
#define DISPLACEMENT_UNIT 2
#define NORMAL_UNIT 3

#define NOISE_INDEX 0
#define H0K_INDEX 1
#define H0_INDEX 2
#define WAVEDATA_INDEX 3
#define DY_INDEX 4
#define DX_DZ_INDEX 5
#define DYX_DYZ_INDEX 6
#define BUTTERFLY_INDEX 7
#define BUFFER_INDEX 8
#define DISPLACEMENT_BUFFER_INDEX 9
#define NORMAL_BUFFER_INDEX 10
#define HEIGHT_INDEX 11
#define DISPLACEMENT_INDEX 12
#define NORMAL_INDEX 13

#define PARAMS_BINDING 16
#define REVERSED_BINDING 17

#define THREAD_NUMBER 8