#pragma once

#define BUFFERS_UNIT 0
#define DEBUG_VIEW_UNIT 1

#define NOISE_INDEX 0
#define H0K_INDEX 1
#define H0_INDEX 2
#define WAVEDATA_INDEX 3
#define DY_INDEX 4
#define DYX_DYZ_INDEX 5
#define BUFFER_INDEX 6
#define DISPLACEMENT_INDEX 7
#define NORMAL_INDEX 8
#define BUTTERFLY_INDEX 9

#define PARAMS_BINDING 16
#define REVERSED_BINDING 17

#define THREAD_NUMBER 8